### ISSUE TITLE
Using a single TS server

### ISSUE THREAD

**Issue by avilesj** [mhartington/nvim-typescript#232]
Since many vim users use ALE for async linting and it pops its own TSServer, is it possible to make `nvim-typescript` use an existing TSServer instead of spawning another one?

**Comment by mhartington** [comment]
It probably should be the other way around. If there's an ALE API for sending tsserver diagnostics, it could be done that. Simply having this plugin reuse another server process is not feasible

**Comment by resolritter** [comment]
@mhartington FWIW ALE does have a function which external sources can call to display diagnostics. https://github.com/dense-analysis/ale/blob/master/autoload/ale/other_source.vim#L12

But I think what the OP is suggesting is that both this plug-in and ALE share the same TSServer process, which to my knowledge is impossible through ALE's API.

An option would be to search the process list and try to attach into a TSServer process if there's one running already, but I'm totally unsure of how feasible that is; just some food for thought.

**Comment by mhartington** [comment]
Interesting, I'll take a look at that. This is more what I was thinking about for diagnostics and hooking into other services

**Comment by ohcibi** [comment]
One important thing to know about ALE is that it does nothing on its own. I.e. if ALE spawns a `tsserver` it is only because of ALE's linter settings include `tsserver` explicitly (`let b:ale_linters = ['tsserver']`). If one tool is able to combine the diagnostics of several tools it is up to the ALE-user to enable that tool only and disable all the others in that configuration to avoid spawning several processes.

Now, if nvim-typescript would delegate every diagnostics of its own `tsserver` process by using ALEs api, a user of both ALE and nvim-typescript could thus simply disable `tsserver` in ALE's settings.

**Comment by mhartington** [comment]
Closing this. I'm not going to be integrating with ALE at the moment.

**Comment by gunar** [comment]
I think `ALE`s behavior has changed since @ohcibi's comment. I didn't explicitly enable `tsserver`, and yet `ALE` was spawning the `tsserver` process. So it seems it's enabled by default now.

Here's how to disable ALE's linter for typescript files, which should fix the problem of having two `tsserver`s running: https://github.com/gunar/dotfiles/commit/0b40c74b1893d0060a10b76d02544e6e4d251976

**Comment by ohcibi** [comment]
@gunar by default ale enables *all* tools that are available in your `PATH`. I know that I was somewhat unspecific on that but my intention was to address the multiple spawned tsserver Problem and not to explain how ale works in general. If you have any trouble using ale, you should post it within one of their community hubs and not in a basically unrelated other repo.
