### ISSUE TITLE
Why better than tsuquyomi?

### ISSUE THREAD

**Issue by whitecolor** [mhartington/nvim-typescript#35]
In what way is it going to be better than https://github.com/Quramy/tsuquyomi and https://github.com/Valloric/YouCompleteMe?

**Comment by mhartington** [comment]
1) tsuquyomi requires vimproc currently, which can be slow for larger projects. Sine this plugin uses neovims remote plugin, I can write the tsserver in a python process instead, which is much faster.
2) Almost no viml. Since this is an remote plugin, almost all of the entire setup can be done using python instead.
3) TS-specific. While YouCompleteMe does have more language support, it is a large plugin that also requires C compilation. Not ideal. This only needs python, the neovim python client, and typescript installed. No compilation needed.

Plus, all of this, is async, so it will not block your editor. AT ALL.

I've used both plugins before, and in fact tsuquyomi is a big inspiration for this project. Better is subjective term, as each one something different. My goal for this was to make a typescript plugin for neovim since it is my main editor.

**Comment by whitecolor** [comment]
I believe these reasons should be added in the main readme, to explain motivation behind the project.

**Comment by HaleTom** [comment]
What are the differences between this and nvim-typescript? #238 https://github.com/Quramy/tsuquyomi/issues/238

**Comment by mhartington** [comment]
Locking this. 1 is not better than the other in my opinion. I built this cus I wanted my own plugin.

From `:h typescript-troubleshooting`

```
Q: Why better than tsuquyomi? Why is this better than other plugins?

A: This plugin does not claim to be better than any other plugin, and is more
   for my own needs. Maybe you would like it too? The plugin is all
   asynchronous and is lag free. Other plugins are not always async or require
   additional plugins that need to be built. If you are using regular Vim, I
   highly suggest Tsuquyomi, especially with Vim 8.
```
