### ISSUE TITLE
More detailed auto complete

### ISSUE THREAD

**Issue by whitecolor** [mhartington/nvim-typescript#36]
What do you think about adding more details like VSCode provides:

![image](https://cloud.githubusercontent.com/assets/736697/22060218/c147593c-dd91-11e6-8b6c-c7e8a59d5d58.png)

When you press (i):

![image](https://cloud.githubusercontent.com/assets/736697/22060247/d971cea2-dd91-11e6-83df-c6edad7655de.png)

In general VScode TS experience (where TS if a first class citizen) could be taken as a role model.

**Comment by mhartington** [comment]
A bit at the mercy of deoplete here. Since it is the completion framework underneath, we can only do so much.

If you bump the size of the max results.

```viml
let g:nvim_typescript#max_completion_detail=100
```

it should give you something like this.

<img width="1680" alt="screen shot 2017-01-18 at 10 28 38 am" src="https://cloud.githubusercontent.com/assets/2835826/22070136/e64ef86c-dd68-11e6-9b1d-79acc49edb91.png">
