### ISSUE TITLE
Sluggishness after update on first insert command

### ISSUE THREAD

**Issue by gsanches** [mhartington/nvim-typescript#42]
I use [dein](https://github.com/Shougo/dein.vim) for controlling my plugins. I deactivated one by one and found this plugin is making Neovim really slow when switching from Normal to Insert mode for the first time. I mean, **really** slow. But only for the first time I go to Insert mode. After the first time, it is normal again.

I never had any similar issues with this plugin before until I updated it today...

**Comment by mhartington** [comment]
I have seen this as well, but i think that deoplete is the culprit. I have not been able to narrow it down, but I get sluggishness when in tmux and just using deoplete.

**Comment by gsanches** [comment]
Wow, it is Deoplete, not your plugin. Sorry to bother, closing...

**Comment by mhartington** [comment]
no no, lets keep this open. I'll talk to @Shougo and see what I can find

**Comment by gsanches** [comment]
No problem! I appreciate your assistance, mate.

**Comment by prabirshrestha** [comment]
I just had similar experience with but different plugin. https://github.com/runoshun/tscompletejob/issues/1#issuecomment-279525172 where initial typescript server takes time to warm up and even crashes vim. More details in the issue. I think this is also related to the same issue or could just be a bug in nvim-typescript but thought it would be good to share.

Here are some of the issues I see:

first typescript server `reload()` call is very slow, especially for large code base as I experienced with [asyncomplete-tscompletejob.vim](https://github.com/prabirshrestha/asyncomplete-tscompletejob.vim). I solved this by adding a status `unknown`, `loading`, `loaded`. if the status is loading getting completion items is a noop.  Here is the commit https://github.com/prabirshrestha/asyncomplete-tscompletejob.vim/commit/5eedc54022ffdc44fc1f4e7e13271ec19513a3a0. But this works well here since asyncomplete sources can be pure async ie. use callbacks.
Another way to temporarily solve this issue would be to have some flag similar to what I had in asyncomplete-tscompletejob.vim. If status is unknown or loading call `reloadAsync()` and return empty array in `gather_candidates`. Only fetch completions if status is loaded. But this would only solve if the first reload is slow. If future reloads or fetching completions are slow one would suffer from the same problem again.

Currently deoplete doesn't support async gather (https://github.com/Shougo/deoplete.nvim/issues/407). This means one bad deoplete source can affect others and possibly vim to as in this case. Ideally deoplete supporting async would solve some of these problems. Way to verify this would be to create a deoplete source that calls `thread.sleep` for 5-10sec and see if vim is responsive or not. I'm not familar with internals of deoplete but this could be one of the reason.

**Comment by mhartington** [comment]
Thanks @prabirshrestha but this doesn't seem to be the issue.

**Comment by mhartington** [comment]
@gsanches can you pull and update?

**Comment by gsanches** [comment]
@mhartington seems to be normal now... for curiosity's sake, what happened?

**Comment by mhartington** [comment]
I was doing a big file lookup in an init function...so yeah, sorry about that 😄 

I've revert the commit that added that and I'm re-working it a bit to not be a slow hog

**Comment by gsanches** [comment]
No problem, mate. Thanks for your attetion, the plugin's nice and the issue is found, keep the good job! :smile:

**Comment by Shougo** [comment]
I will add support the async feature in deoplete.
