### ISSUE TITLE
nvim-completion-manager source

### ISSUE THREAD

**Issue by mhartington** [mhartington/nvim-typescript#45]
https://github.com/roxma/nvim-completion-manager is the new kid on the block, and might be useful to some.

Since the client and completion source are separate, it should be easy to create a source for NCM.

**Comment by roxma** [comment]
`:help NCM-source-examples` contains minimal examples

There are also some relatively small, real examples:

emoji completion (really small): https://github.com/roxma/ncm-github/blob/master/pythonx/cm_sources/github_emoji.py
rust completion: https://github.com/roxma/nvim-cm-racer 

Glad to see this because NCM is missing Typescirpt souce. I've had a glance on [nvim-typescript's deoplete source](https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/deoplete/sources/typescript.py). But unfortunately it's kind of complicated for me, and I'm not a Typescript guy either. So I may not create PR for this in a (long?) while.

Asks me for any questions.
