### ISSUE TITLE
No candidates appear

### ISSUE THREAD

**Issue by uzimith** [mhartington/nvim-typescript#46]
# Problems summary

I can't see any candidates from this source.

I have used `nvim-typescript`. However, when I enter typescript buffer, I got a little time freeze everytime. I guessed that was TSServer staring time, so I tried reinstall, and I got this situation.

## Expected

I want completion like README.md screenshot.

## Environment Information

 * terminal: iTerm 2 Build 3.0.14 / tmux 2.3
 * vim/nvim version: nvim 0.1.7
 * OS: MaxOS Sierra 10.12.3 

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif

let s:dein_dir = expand('~/.cache/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir)

  call dein#add('Shougo/deoplete.nvim')
  call dein#add('mhartington/nvim-typescript')
  call dein#add('HerringtonDarkholme/yats.vim')

  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
  "call :UpdateRemotePlugins
endif
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_debug = 1
let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', 'deoplete.log')
```

## The reproduce ways from neovim starting

1. start nvim
2. :UpdateRemotePlugins
3. start typing
4. I can't see any candidates from this source.

## Example project repo?

Sorry, this is not a minimal project.

https://github.com/uzimith/twitch-comment/tree/nvim-typescript

### When I didn't call :TSStart
![yvedohtgki](https://cloud.githubusercontent.com/assets/365836/23821925/e38bcef4-0683-11e7-8752-3b7bcc4bdadd.gif)

<img width="1030" alt="screen shot 2017-03-11 at 17 23 33" src="https://cloud.githubusercontent.com/assets/365836/23821759/98caf358-067f-11e7-89ca-ec5219005504.png">

### When I call :TSStart
![a](https://cloud.githubusercontent.com/assets/365836/23822045/58c16050-0687-11e7-8704-4587338e1c8f.gif)

Sometimes I can see some candidates from other sources.

![5p9svra1rn](https://cloud.githubusercontent.com/assets/365836/23821937/2027b4b8-0684-11e7-945b-11811fcb7be5.gif)

**Comment by mhartington** [comment]
### What is happening
Hmm first glance, it appears to be an issue where the `pwd` and the tsconfig are not in the same directory.

From the clone of the project and your gifs, I'm seeing:

1) your pwd when you start nvim is `src/`
2) your tsconfig.json is actually in your `./` directory 


### Why this is happening
Right now I do some checks for either a tsconfig.json or a jsconfig.json (for javascript projects).
If those files do not exist, the server cannot be started since it will not know how to read your project.

### Possible fix
Right now I'm only searching for that config file if it exist in the current directory or any child directory. 
A quick fix is to either

- cd to the root directory and start vim from there

- move the tsconfig.json to the src directory.

![issue-46](https://cloud.githubusercontent.com/assets/2835826/23823853/305653b2-0639-11e7-9940-855b3f43f9a2.gif)


Here's an example of moving the tsconfig.json to the src directory.

Or you could even create a symlink as well.

**Comment by uzimith** [comment]
I created symlinks.

```
ln -s ../tsconfig.json ./
```

And now works well! Thank you!

I don't understand `.tsconfig` searching behavior because TSServer works even in children foler now, but could you include `.git` folder for `.tsconfig` searching path?

I wanted to put `.tsconfig` in root. I guess we can get gitroot path (like `git rev-parse --show-toplevel`), so it'll works well.

**Comment by mhartington** [comment]
So the root search will use this line here

https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/nvim-typescript/dir.py#L9

So as soon as you start nvim, it will treat that directory as the root. I guess we could also do an if statement

```python
if('git rev-parse --show-toplevel'):
  # set current project root to that
else: 
  # set project root to cwd
```

**Comment by uzimith** [comment]
I read around here. What you said is very cool!

**Comment by mhartington** [comment]
Sorry for the silence on my end. Can you pull the latest and give it a test?

**Comment by mhartington** [comment]
Closing as there has been no reply. If this issue still happens, please feel free to open a NEW issue.
